name: Update Serie A EPG

# تشغيل يوميًا + إمكانية التشغيل يدويًا
on:
  schedule:
    - cron: '0 2 * * *' # كل يوم الساعة 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run EPG script
      run: python epg.py

    - name: Commit and push epg.xml
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add epg.xml
        git commit -m "Update EPG $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
